name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==3.8.0
      - cloudpickle==3.1.2
      - numpy==1.26.4
      - pandas==2.1.4
      - scikit-learn==1.3.2
      - scipy==1.10.1