# -*- coding: utf-8 -*-
"""Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jBORnw4FMl1gN1iJVBT_QqNWS8W0bAXi
"""

import pandas as pd
import numpy as np
import joblib
import mlflow
import mlflow.sklearn

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("heart_disease_clean.csv")
df.head()

df.columns

# Binary classification
df["num"] = (df["num"] > 0).astype(int)

X = df.drop(columns=["num"])
y = df["num"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

mlflow.autolog()
with mlflow.start_run():

    lr = LogisticRegression(max_iter=1000)
    lr.fit(X_train_scaled, y_train)

    y_pred_lr = lr.predict(X_test_scaled)

    acc_lr = accuracy_score(y_test, y_pred_lr)
    print("Accuracy LR:", acc_lr)

    mlflow.log_metric("accuracy_lr", acc_lr)

with mlflow.start_run(run_name="RandomForest"):

    rf = RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        random_state=42
    )

    rf.fit(X_train, y_train)
    y_pred_rf = rf.predict(X_test)

    acc_rf = accuracy_score(y_test, y_pred_rf)
    print("Accuracy RF:", acc_rf)

    mlflow.log_metric("accuracy_rf", acc_rf)

    mlflow.sklearn.log_model(rf, "model")

joblib.dump(rf, "model_rf.pkl")
joblib.dump(scaler, "scaler.pkl")