name: Train ML Model

on:
  push:
    branches: [ "main" ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install MLflow
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Run MLflow Project
      run: mlflow run MLProject